---
development:
  cloud_name: bookmarks-rails
  api_key: <%= ENV.fetch('API_KEY') %>
  api_secret: <%= ENV.fetch('API_SECRET') %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: bookmarks-rails
  api_key: <%= ENV.fetch('API_KEY') %>
  api_secret: <%= ENV.fetch('API_SECRET') %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: bookmarks-rails
  api_key: <%= ENV.fetch('API_KEY') %>
  api_secret: <%= ENV.fetch('API_SECRET') %>
  enhance_image_tag: true
  static_image_support: false
